Aquila/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^dbms/', include('dbms.urls')),
    url(r'^', include('cmdb.urls')),

]

cmdb/urls.py
#!/bin/env python3
# _*_ coding:utf8 _*_

from django.conf.urls import url

from cmdb import views
from django.views import View

urlpatterns = [
    url(r'login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^user', views.user_manager, name='user_manager'),
    url(r'^backend/$', views.backend, name='backend'),
    url(r'^backend/group_del.html$', views.group_del, name='group_del'),
    url(r'^backend/hostgroup_manage.html$', views.hostgroup_manage, name='hostgroup_manage'),
    url(r'backend/hostgroup_append.html$', views.hostgroup_append, name='cmdb_hostgroup_append'),
    url(r'backend/host_manage.html$', views.host_manage, name='cmdb_host_manage'),
    url(r'backend/host_append.html$', views.host_append, name='cmdb_host_append'),
]

dbms/models.py
from django.db import models
# 备份恢复相关的表结构


class MysqlBackupSourceInfo(models.Model):
    id = models.AutoField(primary_key=True)
    generator_room_name = models.CharField(max_length=30)
    ipaddr = models.UnsignedIntegerField()
    port = models.UnsignedSmallIntegerField()
    service_level = models.TinyIntegerField()
    defaults_file = models.CharField(max_length=100)
    back_time = models.TimeField()
    transport_time = models.TimeField(default='1980-01-01 01:01:01')
    is_transport = models.SmallIntegerField(default=0)
    back_pool_id = models.ForeignKey('BackupPoolInfo', on_delete=models.CASCADE, db_constraint=False)
    r_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'dbms_mysql_backup_source_info'
        unique_together = ('generator_room_name', 'ipaddr', 'port')


class BackupPoolInfo(models.Model):
    id = models.AutoField(primary_key=True)
    pool_name = models.CharField(max_length=50)
    ipaddr = models.IntegerField()
    port = models.UnsignedSmallIntegerField()
    passwd = models.CharField(max_length=50)
    username = models.CharField(max_length=50)

    class Meta:
        db_table = 'dbms_mysql_backup_pool_source_info'


class BackupedBinlogInfo(models.Model):
    id = models.AutoField(primary_key=True)
    machine_id = models.ForeignKey('MysqlBackupSourceInfo', on_delete=models.CASCADE, db_constraint=False)
    binlog_name = models.CharField(max_length=50)
    binlog_create_time = models.DateTimeField()
    binlog_size = models.UnsignedSmallIntegerField()
    r_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'dbms_mysql_backuped_binlog_info'
        index_together = ('machine_id', 'r_time')


class BackupedInfo(models.Model):
    id = models.AutoField(primary_key=True)
    machine_id = models.ForeignKey('MysqlBackupSourceInfo', on_delete=models.CASCADE, db_constraint=False)
    backup_name = models.CharField(max_length=100)
    backup_file_path = models.CharField(max_length=100)
    backup_druation = models.UnsignedSmallIntegerField()
    backup_status = models.TinyIntegerField()
    binlog_file_path = models.CharField(max_length=100)
    binlog_index = models.CharField(max_length=100)
    binlog_start = models.CharField(max_length=50)
    binlog_end = models.CharField(max_length=50)
    binlog_backup_status = models.TinyIntegerField(default=0)
    binlog_backup_piece = models.CharField(max_length=50)
    r_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'dbms_mysql_backuped_info'
        index_together = ('machine_id', 'r_time', 'backup_status')


# sql发布相关表结构
class InceptionWorkOrderInfo(models.Model):
    id = models.AutoField(primary_key=True)
    work_order_id = models.BigIntegerField(unique=True)
    work_user = models.CharField(max_length=50)
    db_host = models.CharField(max_length=45)
    db_name = models.CharField(max_length=50, default='test_db')
    end_time = models.DateTimeField(default='1980-01-01 01:01:01')
    review_user = models.CharField(max_length=50)
    review_time = models.DateTimeField(default='1980-01-01 01:01:01')
    review_status = models.TinyIntegerField(default=10)    # 10表示未审核， 0 表示通过， 1表示驳回
    work_status = models.TinyIntegerField(default=10)      # 10表示未执行， 0 表示执行成功， 1表示执行失败, 2.进行执行队列， 3, 正在执行
    r_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'dbms_ince_work_order_info'


class InceptionAuditDetail(models.Model):
    id = models.AutoField(primary_key=True)
    work_order = models.ForeignKey(to='InceptionWorkOrderInfo', on_delete=models.CASCADE, to_field='work_order_id', db_constraint=False)
    sql_sid = models.UnsignedSmallIntegerField()              # 工单中的sql序号
    status = models.UnsignedSmallIntegerField()               # RERUN,CHECKED, EXECUTED, None 0,1,2,3
    err_id = models.UnsignedSmallIntegerField()               # 0, 1, 2
    stage_status = models.UnsignedSmallIntegerField()         # Audit completed： 0，Execute failed：1，  Execute Successfully：2, Execute Successfully\nBackup successfully：3, Execute Successfully\nBackup filed ：4
    error_msg = models.TextField()             # None, str,
    sql_content = models.TextField()           # sql内容
    aff_row = models.IntegerField()              # 影响的行数
    rollback_id = models.CharField(max_length=50)             # rollback_id
    backup_dbname = models.CharField(max_length=100)          # 存放备份的库名
    execute_time = models.IntegerField()                      # sql 执行好时，*1000， 按毫秒存放
    sql_hash = models.CharField(max_length=50)                # 用于 使用pt-osc 工具时查看进度, None
    r_time = models.DateTimeField(auto_now_add=True)         # 记录生成时间

    class Meta:
        db_table = 'dbms_ince_audit_detail'


class InceptionWorkSQL(models.Model):
    id = models.AutoField(primary_key=True)
    work_order = models.ForeignKey('InceptionWorkOrderInfo', on_delete=models.CASCADE, to_field='work_order_id', db_constraint=False)
    sql_content = models.TextField()

    class Meta:
        db_table = 'dbms_ince_work_sql_content'


class WorkOrderTask(models.Model):
    host_ip = models.CharField(max_length=45)
    app_user = models.CharField(max_length=20)
    app_pass = models.CharField(max_length=30)
    app_port = models.SmallIntegerField()
    wid = models.BigIntegerField(unique=True)

templates/audit_details.html
{% load udf_filter %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>工单审核</title>
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div style="margin: 10px">
{% for item in work_info %}
    <span>工单号:{{ item.work_order_id }}</span>
    <span>工单发起人:{{ item.work_user }}</span>
    <span>工单发起时间:{{ item.r_time }}</span>
{% endfor %}
    <div class="btn-group"}>
      <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        审核 <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><a href="#">通过</a></li>
        <li><a href="#">驳回</a></li>
      </ul>
    </div>
</div>
<div>
    <table class="table table-hover" >
    <thead>
        <tr>
            <th>id</th>
            <th>执行状态</th>
            <th>错误代码</th>
            <th>语句状态</th>
            <th>错误信息</th>
            <th>sql内容</th>
            <th>影响行数</th>
            <th>回滚id</th>
            <th>恢复库名</th>
            <th>执行时间</th>
            <th>SqlHash</th>
        </tr>
    </thead>
    {% for items in detail_result %}
        <tr>
        <td>{{ items.sql_sid }}</td>
        <td>{{ items.status }}</td>
        <td>{{ items.err_id}}</td>
        <td>
            {% if items.error_msg == "None" %}
                {{ None}}
            {% else %}
                {% for line in  items.error_msg|udf_split %}
                    <p>{{ line }}</p>
                {% endfor %}
            {% endif %}

        </td>
        <td>{{ items.stage_status }}</td>
        <td>{{ items.sql_content }}</td>
        <td>{{ items.aff_row }}</td>
        <td>{{ items.rollback_id }}</td>
        <td>{{ items.backup_dbname }}</td>
        <td>{{ items.execute_time }}</td>
        <td>{{ items.sql_hash }}</td>

        </tr>
    {% endfor %}
    </table>
</div>
</body>
<script src="/static/vendor/jquery/jquery.min.js"></script>
<script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
</html>

templates/audit_details_shade_layer.html
<div class="shade_layer check_dis_flag" >
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-body" id="group_add_text">
                <form id="form" role="form"  method="post">
                    <fieldset style="opacity:1">
                        <div><i id="exit_edit" class="fa fa-times" aria-hidden="true"></i></div>

                        <div class="btn-group"}>
                          <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            审核 <span class="caret"></span>
                          </button>
                          <ul class="dropdown-menu">
                            <li><a href="#">通过</a></li>
                            <li><a href="#">驳回</a></li>
                          </ul>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %} {% endblock %}</title>
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <link href="/static/css/admin-2.css" rel="stylesheet">
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    {% block css_flag %}{% endblock %}

</head>

<body>
    <div id="wrapper">
        <!-- 头部标签 -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'index' %}">Aquila OS</a>
            </div>
            <ul class="nav navbar-top-links navbar-right">
                <li><a href="{% url 'login' %}"><i class="fa fa-sign-out fa-fw"></i> 退出登录</a>
            </ul>
            <ul class="nav navbar-top-links navbar-right">

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i>
                            <span>
                                {{ userinfo.user_name }}
                            </span>
{#                            <i class="fa fa-caret-down"></i>#}
                        </a>
{#                        <ul class="dropdown-menu dropdown-user">#}
{#                            <li><a href="{% url 'backend' %}"><i class="fa fa-user fa-fw"></i> 后台管理</a>#}
{#                            </li>#}
{##}
{#                        </ul>#}
                    </li>




            </ul>
             <!-- 左侧菜单栏 -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="{% url 'index' %}"><i class="fa fa-dashboard fa-fw"></i> 仪表盘</a>
                        </li>
                        {% if userinfo.role.user_role_jd == '超级管理员' %}
                            <li>
                                <a href="#"><i class="fa fa-database fa-fw"></i> CMDB<span class="fa arrow"></span></a>
                                <ul class="nav nav-second-level collapse">
                                    <li>
                                        <a>主机管理<span class="fa arrow"></span></a>
                                        <ul class="nav nav-third-level">
                                            <li>
                                                <a href="{% url 'hostgroup_manage' %}">主机组管理</a>
                                            </li>
                                            <li>
                                                <a href="{% url 'cmdb_host_manage' %}">主机管理</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a>用户管理<span class="fa arrow"></span></a>
                                        <ul class="nav nav-third-level">
                                            <li>
                                                <a href="#">用户组管理</a>
                                            </li>
                                            <li>
                                                <a href="#">用户管理</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li>
                                        <a>权限管理<span class="fa arrow"></span></a>
                                        <ul class="nav nav-third-level">
                                            <li>
                                                <a href="#">用户权限</a>
                                            </li>
                                            <li>
                                                <a href="#">用户组权限</a>
                                            </li>
                                        </ul>
                                    </li>

                                </ul>
                            </li>
                        {% endif %}
                        <li>
                            <a href="#"><i class="fa fa-database fa-fw" aria-hidden="true"></i> RDBMS<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a>性能分析<span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="#">慢SQL优化</a>
                                        </li>
                                        <li>
                                            <a href="#">SQLAdvisor</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a>SQL 发布<span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="{% url 'dbms_sql_reviews' %}">SQL 提交</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'dbms_sql_audit' %}">SQL 审核</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'dbms_work_runing' %}">SQL 执行</a>
                                        </li>
                                        <li>
                                            <a href="{% url 'dbms_work_reviews' %}">工单查询</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a>备份与恢复<span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="{% url 'backup' %}">备份</a>
                                        </li>
                                        <li>
                                            <a href="#">恢复</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a>实例安装<span class="fa arrow"></span></a>
                                    <ul class="nav nav-third-level">
                                        <li>
                                            <a href="{% url 'install' %}">单机</a>
                                        </li>
                                        <li>
                                            <a href="#">MHA</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </div>

     <!-- 内容主体 -->
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h6 class="page-header"></h6>
            </div>
        </div>
        {% block body_body %}

        {% endblock %}
    </div>


</body>
<script src="/static/vendor/jquery/jquery.min.js"></script>
<script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/vendor/metisMenu/metisMenu.min.js"></script>
<script src="/static/vendor/raphael/raphael.min.js"></script>
<script src="/static/vendor/morrisjs/morris.min.js"></script>
<script src="/static/jss/admin-2.js"></script>
{% block jss_flag %}{% endblock %}
</html>

templates/host.html
{% include 'shade_layer.html' %}

<div class="col-lg-12">
    <div class="panel">
        <div class="panel-body">
            <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel">
                            <div>
                                <button id="host_group_append" type="button" class="btn btn-primary">添加主机</button>
                                <button id="host_delete" type="button" class="btn btn-danger" style="margin-left: 200px;">批量删除</button>
                            </div>
                            <div class="panel-body">
                                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th style="display: none;"></th>
                                            <th>选择</th>
                                            <th>主机地址</th>
                                            <th>应用类型</th>
                                            <th>主机组</th>
                                            <th>主机用户</th>
                                            <th>主机密码</th>
                                            <th>主机端口</th>
                                            <th>操作</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% if host_list %}
                                            {% for item in host_list %}
                                                <tr id="host">
                                                    <td id="host_id" style="display: none;">{{ item.id }}</td>
                                                    <td><input type="checkbox" /></td>
                                                    <td id="num_to_ip">{{ item.host_ip }}</td>
                                                    <td id="app_type">{{ item.app_type }}</td>
                                                    <td id="host_group_id">{{ item.host_group }}</td>
                                                    <td id="host_user">{{ item.host_user }}</td>
                                                    <td id="host_pass">{{ item.host_pass }}</td>
                                                    <td id="host_port">{{ item.host_port }}</td>
                                                    <td><button id="host_update" type="button" class="btn btn-primary" style="margin-left: 10px;">编辑</button></td>
                                                </tr>
                                            {% endfor %}
                                        {% endif %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/host_manage.html
{% extends 'backend.html' %}
<!--继承基础模板-->
    {% block css_flag %}
    <link rel="stylesheet" href="/static/css/iframe_host_manage.css"/>
        <link href="/static/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="/static/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
    {% endblock %}

<!--修改基础模板中的 title 标签-->
{% block title %}HostGroup Manage{% endblock %}

    <!--修改主体标题-->
    {% block body_title %}
        HostGroup Manage
    {% endblock %}

    <!--修改主体内容-->
    {% block body_body %}
        <!--导入sql提交表单-->
{#        {% include 'host.html' %}#}
    {% endblock %}

{% block jss_flag %}
    <script src="/static/vendor/datatables/js/jquery.dataTables.js"></script>
    <script src="/static/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="/static/vendor/datatables-responsive/dataTables.responsive.js"></script>
    <script src="/static/jss/host_opertion.js"></script>
    <script src="/static/jss/jquery.cookie.js"></script>
{% endblock %}

templates/hostgroup.html
{% include 'shade_layer.html' %}

<div class="col-lg-12">
    <div class="panel">
        <div class="panel-body">
            <div id="dataTables-example_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel">
                            <div>
                                <button id="host_group_append" type="button" class="btn btn-primary">添加主机组</button>
                                <button id="host_delete" type="button" class="btn btn-danger" style="margin-left: 200px;">批量删除</button>
{#                                <button id="host_group_update" type="button" class="btn btn-primary" style="margin-left: 10px;">Update</button>#}
{#                                  <button id="host_group_delete" type="button" class="btn btn-danger" style="margin-left: 200px;">批量删除</button>#}
                                <!-- <button type="button" class="btn btn-success">（成功）Success</button>-->
                                <!-- <button type="button" class="btn btn-info">（一般信息）Info</button>-->
                                <!-- <button type="button" class="btn btn-warning">（警告）Warning</button>-->
                            </div>
                            <div class="panel-body">
                                <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                        <tr>
                                            <th style="display: none;"></th>
                                            <th>选择</th>
                                            <th>组名称</th>
                                            <th>主机组说明</th>
                                            <th>操作</th>

                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% if hostgroup_list %}
                                            {% for item in hostgroup_list %}
                                                <tr id="hostgroup">
                                                    <td id="hostgroup_id" style="display: none;">{{ item.id }}</td>
                                                    <td><input type="checkbox" /></td>
                                                    <td id="group_name"><span>{{ item.host_group_name }}</span></td>
                                                    <td id="group_jd"><span>{{ item.host_group_jd }}</span></td>
                                                    <td><button id="host_group_update" type="button" class="btn btn-primary" style="margin-left: 10px;">编辑</button></td>
                                                </tr>
                                            {% endfor %}
                                        {% endif %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/hostgroup_append.html
    <div class="form-group">
        <input id="groupid" style="display: none;"></input>
        <span>GroupName</span>
        <input id="groupname" class="form-control" name="groupname" type="text" />
    </div>
    <div class="form-group">
        <span>Description</span>
        <input id="groupdesc" class="form-control"  name="groupdesc" type="text" />
    </div>
    <div style="color: red;">
        <p id="groupadd_err_msg">
        </p>
    </div>
     <input id="group_add_button" type="button" class="btn btn-lg btn-primary btn-block"  value="Commit"/>

templates/index.html
{% extends 'base.html' %}
{% block title %} index {% endblock %}

templates/manage.html
{% extends 'cmdb_manage.html' %}

    {% block body_title %}
        Host Manage
    {% endblock %}

{% block body_body %}
        <!--导入sql提交表单-->
    {% if request_path == '/backend/host_manage.html' %}
        {% include 'host.html' %}
{#  {% elif request_path == '/backend/hostgroup_manage.html' %}#}
{#      {% include 'hostgroup.html' %}#}
    {% else %}
        {% include 'hostgroup.html' %}
    {% endif %}
{% endblock %}

templates/shade_layer.html
<div class="shade_layer check_dis_flag" >
    <div class="col-md-4 col-md-offset-4">
        <div class="login-panel panel panel-default">
            <div class="panel-body" id="group_add_text">
                    <fieldset style="opacity:1">
                        <div><i id="exit_edit" class="fa fa-times" aria-hidden="true"></i></div>
                        {% if request_path == '/backend/host_manage.html' %}
                            {% include 'host_append.html' %}
{#                        {% elif request_path == '/backend/hostgroup_manage.html' %}#}
{#                            {% include 'hostgroup.html' %}#}
                        {% else %}
                            {% include 'hostgroup_append.html' %}
                        {% endif %}
                    </fieldset>
            </div>
        </div>
    </div>
</div>

templates/work_runing.html
{% extends 'base.html' %}


 {% block css_flag %}

        <link href="/static/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet">

        <!-- DataTables Responsive CSS -->
        <link href="/static/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet">
        <link rel="stylesheet" href="/static/css/iframe_host_manage.css"/>
{% endblock %}



{% block body_body %}


    <div class="panel-body" id="table_ip_num">
        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
        <thead>
        <tr>
            <td>工单号</td>
            <td>主库地址</td>
            <td>库名</td>
            <td>sql 文本内容</td>
            <td>提交时间</td>
            <td>审核人</td>
            <td>工单状态</td>
            <td>操作</td>
        </tr>
        </thead>
        <tbody>
            {% for row in all_work %}
                <tr>
                    <td id="wid">{{ row.work_order_id }}</td>
                    <td id="host_ip">{{ row.db_host }}</td>
                    <td>{{ row.db_name }}</td>

                    <td id="sql_content">{{ row.inceptionworksql_set.all.0.sql_content }}</td>
                    <td>{{ row.r_time }}</td>
                    <td>{{ row.review_user }}</td>
                    <td>
                        {% if row.work_status == 10 %}
                            <span class="sql_audit_info sql_audit_info_info">未执行</span>
                        {% elif row.work_status == 0 %}
                            <span class="sql_audit_info sql_audit_info_success">执行成功</span>
                        {% else %}
                            <span class="sql_audit_info sql_audit_info_warning">执行失败</span>
                        {% endif %}
                    </td>
                    <td>
                        <input id="workruning_smt" type="submit" class="work_runing" value="执行工单"/>
                    </td>

                </tr>

            {% endfor %}
        </tbody>
        </table>
    </div>







{% endblock %}

{% block jss_flag %}
    <script src="/static/vendor/datatables/js/jquery.dataTables.js"></script>
    <script src="/static/jss/jquery.cookie.js"></script>
    <script src="/static/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="/static/vendor/datatables-responsive/dataTables.responsive.js"></script>

    <script src="/static/jss/host_opertion.js"></script>
{% endblock %}